name: Dev CI

on:
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          architecture: x64

      - name: Clean and build
        run: mvn -B -e clean install -DskipTests

      - name: Run tests
        run: ./mvnw -B -e verify
